pipeline {
    agent any
    tools {
        maven 'Maven3'
        jdk 'JDK17'
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/RIT2006ESH/SpringSecurity.git'
            }
        }
        stage('Build') {
            steps {
                dir('spring_security') {
                    bat 'mvn clean install -DskipTests'
                }
            }
        }
        stage('Test') {
            steps {
                dir('spring_security') {
                    bat 'mvn test'
                }
            }
        }
        stage('Deploy') {
            steps {
                dir('spring_security') {
                    // Stop any running instance of the app
                    bat '''
                        for /f "tokens=5" %%a in ('netstat -aon ^| find ":8080" ^| find "LISTENING"') do (
                            taskkill /F /PID %%a
                        )
                        exit /b 0
                    '''
                    // Start the new jar in background
                    bat '''
                        start /B java -jar target\\spring_security-0.0.1-SNAPSHOT.jar
                    '''
                    echo 'Application deployed on http://localhost:8080'
                }
            }
        }
    }
    post {
        success {
            echo 'Build and deployment succeeded!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}